### ISSUE TITLE
Where is notes.exe? And Windows 11 flags Hunted Editor.exe

### ISSUE THREAD

**Issue by WinAndy** [RemnantETS/AuriHellMod#24]
In your Youtube video about modding Remnant, you use notes.exe, and you got a link to it here on GitHub, but the link leads to a webpage on GitHub where I can't find any notes.exe, only Hunted Editor.exe. Windows 11 warns that Hunted Editor.exe can harm my computer.

**Comment by Auricrystal** [comment]
Notes.exe and Hunted Editor.exe are the same file just renamed to show ownership of the designer of the application rather than a default generic name, the warning is just because it is a custom program with no signature so windows is unsure of its origin,
